version: "2"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: rapidpro-basic:local
        links:
            - "db:postgres"
            - "redis:redis"
        volumes:
            - "./:/app"
        environment:
            VIRTUAL_HOST: rapidpro.local.aldryn.net

    db:
        image: mdillon/postgis:9.4
        volumes:
            - "./postgres_extensions.sh:/docker-entrypoint-initdb.d/q_extensions.sh"
        environment:
            POSTGRES_USER: temba
            POSTGRES_PASSWORD: temba
            POSTGRES_DB: temba

    redis:
        image: redis:3.2-alpine
